sudo: false
language: node_js
node_js: "8"
install:
- travis_retry gem install s3_website -v 3.4.0
- travis_retry npm ci
before_script:
- npx jest
- npm run build
script: ./s3_deploy.sh
cache:
  bundler: true
  directories:
    - "$HOME/.npm"
