sudo: false
language: node_js
node_js: "8"
before_install:
  - npm i -g 'npm@^6.4.0'
install:
- travis_retry gem install s3_website -v 3.4.0
- travis_retry npm ci
script:
- npx jest
- npm run build
after_script: ./s3_deploy.sh
cache:
  bundler: true
  directories:
    - "$HOME/.npm"
